### ISSUE TITLE
Latest version v0.13.0 causing issue when zooming in or out

### ISSUE THREAD

**Issue by glchua2** [mapgears/ol3-google-maps#151] opened 2016-12-14 09:49 UTC
When performing a zooming in or zooming out action there is now an additional panning before the zoom. It can be observed in this example [here](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/simple.html).

This panning somehow solve the issues depicted in this [ticket](https://github.com/mapgears/ol3-google-maps/issues/134).

**Comment by adube** [comment] 2016-12-14 13:02
Thanks for reporting this.  I'll have a look at it.

**Comment by adube** [comment] 2016-12-14 14:41
@glchua2 I have excellent news!

First, I'd like to apologize.  I released 0.13 without testing rigorously the examples.  I assumed that since the build worked, everything was fine.  Terrible mistake.  Sorry about that.

So, I found the culprit, which turned out to be like finding the Holy Grail!  See: https://github.com/openlayers/ol3/releases/tag/v3.20.0  OpenLayers changed the way the animation work in 3.20.  Now, while zooming or panning, the actual center and resolution are updated **while** animating.  It used to be set the the **end** before, only once.  This caused the maps (OpenLayers and Google) to be not perfectly synchronized.  That's no longer the case!

This means that we no longer need to make Google Maps draw the conterparts from ol3.  We can make both of them perfectly synchronized while OpenLayers animates.  That wasn't possible before 3.20.

I'm all excited, now! This is a huge step towards having an OpenLayers map on top of Google Maps and have it do what we want using plain OpenLayers code.  This can even result in cleaning up what will no longer be needed and release a 1.0!  Almost everything mentioned in the "LIMITATIONS" could be swiped away.

**For now**, I'll make a fix and re-release a 0.13.1 asap.  I'll let you know once that's done.

**Comment by adube** [comment] 2016-12-14 15:49
The regression has been fixed in #152.  A new [0.13.1 release](https://github.com/mapgears/ol3-google-maps/releases/tag/v0.13.1) has been created.

You can try the [example](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/simple.html) again to see that the issue is gone now.

Thanks again for reporting this.

**Closed as completed by adube** 2016-12-14 15:49 UTC
Labels: bug

**Comment by glchua2** [comment] 2016-12-15 02:18
@adube That is great news!!

While trying out the example, i can verify that the issue is indeed gone. But, now every time i zoom in or out, the google map layer will turn grey first before it render finish. The contrast is more apparent when comparing it to osm layer [here](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/concept.html).

**Comment by adube** [comment] 2016-12-15 13:14
Thanks for reporting this.  I opened an other issue about this: #153.
