### ISSUE TITLE
AuthenticationService.Authenticate on Google Map

### ISSUE THREAD

**Issue by ghost** [mapgears/ol3-google-maps#38] opened 2016-01-19 03:34 UTC
I have two maps to be used on my site
the first map is used for editing such geometries, inserting polygons, etc.
the second map is used for viewing only and it is in a different location on the the site from the first map

BTW, im only using localhost and this is what the AuthenticationSerivce.Authenticate

```
/**/_xdc_._kif0ek && _xdc_._kif0ek( [1, null, 0] )
0: 1
1: null
2: 0
```

P.S.
Sorry if this lacks, but i can edit this. My first time seeking help on github since ol3gm is only available here.

**Comment by adube** [comment] 2016-01-19 13:49
Hello there.  Thanks for your interest in olgm.

I'm not sure I understand what you're asking.  Would you please elaborate more ?  If you're facing an issue, it would be nice if you could reproduce it in a small jsfiddle example that would demonstrate it and make it easier to debug it.

**Comment by adube** [comment] 2016-01-21 15:22
@brynrmrk, I got your e-mail.  Please, use this thread instead to send details about your issue.

I also noticed that you didn't explain the source of the problem.  What isn't working ?  What are you trying to accomplish ?  You can share pieces of code of what you did if you can't create a JSFiddle.

Help us help you :)

**Comment by ghost** [comment] 2016-01-22 03:21
Hello @adube , i haven't figured out the problem yet, 
btw here's the fiddle, i'd successfully make it sorry if I emailed you because i was having trouble making a jsfiddle

Site that ol3gm does not work
http://jsfiddle.net/v3c9s4e2/7/

Site the ol3gm work
http://jsfiddle.net/L5ncnwo3/5/

i cant figure out the problem since both have AuthenticationService.Authenticate in their network console

P.S:
sorry if the code looks rubbish

EDIT: 1/24/16
removed the codes that's not used, sorry forgot to remove it from the start

**Comment by adube** [comment] 2016-01-22 20:40
Hi @brynrmrk 

I looked at your code it is too complex for me to quickly understand and spot where the issue is.  You either need to create a much smaller version of the application, one that is minimized to just a couple number of lines of JavaScript code where we could easily identify the problem, otherwise you could attempt to ask for Commercial Support at info@mapgears.com.

**Comment by ghost** [comment] 2016-01-29 03:25
hello @adube here is it jsfiddle of the shoretened code

Site that ol3gm does not work
http://jsfiddle.net/v3c9s4e2/10/ **WORKING NOW, REMOVED MIN- & MAX-**

Site the ol3gm work
http://jsfiddle.net/L5ncnwo3/6/ **WORKING REMOVED MIN- & MAX-**

**Comment by alexbrault** [comment] 2016-01-29 05:40
I've found the culprit(s). When you include a google layer, Google Maps takes over the container and it doesn't honour the min-height and max-height attributes in the css file (Presumable, the min- and max-width attributes might also have issues). I'm not sure whether this is an olGM bug or a Google Maps limitation; in the meantime, you can use the `height` attribute to set a fixed height

Additionally, Google Maps doesn't like fractional zoom levels (OL3 on the other hand handles them like a champ). Use `zoom: 10` in your view to fix this. Again, not sure whether the issues stems from olgm or Google Maps.

I'll let @adube investigate further as appropriate

**Comment by ghost** [comment] 2016-02-01 05:35
Hello @alexbrault 

Thanks for the help, I couldn't guess that the `zoom`could be the problem since I've only tried OL3 and it accepts whatever fractional zoom I've entered. About the min- and max-, I've tried removing it and it doesn't show any error(s).

**Comment by adube** [comment] 2016-07-22 19:40
I'm closing this issue since it hasn't had any late activities,

**Comment by adube** [comment] 2024-02-26 14:23
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352

**Closed as not planned by adube** 2024-02-26 14:23 UTC
Labels: help wanted
