### ISSUE TITLE
map images dont load after zoom

### ISSUE THREAD

**Issue by luckylooke** [mapgears/ol3-google-maps#160] opened 2017-02-02 15:01 UTC
All examples are not loading map after zoom: http://mapgears.github.io/ol3-google-maps/examples/

**Comment by luckylooke** [comment] 2017-02-02 15:05
Zoom with buttons works, map just greyed out during the transition. But zooming with scroll is when bug occurs.

**Comment by adube** [comment] 2017-02-02 15:20
This is a duplicate of #153.  Thanks for your interest in OL3GM.

**Comment by luckylooke** [comment] 2017-02-02 17:31
@adube I dont think is duplicate of #153. Because now map doesn't load at all. They are not grey only while transition, but they stay grey. So it is more serious bug now. But I think it occurs because of some change on google maps API. Because it occurs without changing the code or your library.

**Comment by luckylooke** [comment] 2017-02-02 17:35
This is screenshot of how it looks like after zoom and it stay in that state: http://prntscr.com/e3nm2p

**Comment by luckylooke** [comment] 2017-02-02 17:37
Tested on Safari, Firefox and Chrome.. all on OSX, all with same result.

**Comment by adube** [comment] 2017-02-02 18:27
I'm not currently able to reproduce the issue from the examples on http://mapgears.github.io/ol3-google-maps/examples/

I checked from my Linux machine, from Windows and I also asked a colleague and it worked fine.  We see the grey while the transition occurs, but not after.

I'll leave this open.  If you're able to test on other environments or provide a way to always reproduce the issue, you can report it here.

**Comment by luckylooke** [comment] 2017-02-02 19:17
Ok, I have just tested on win machine and it was OK, so it seems to be just Mac/OSX related. So my OSX: 10.12.2 (16C68) Sierra, Chrome Version 56.0.2924.87 (64-bit), screencast of bug: https://www.youtube.com/watch?v=wi_bQKMC6zE

**Comment by adube** [comment] 2017-02-02 19:20
Thanks for testing this.  We have a Mac machine at the office, so I'll give it a shot from there.  I'll let you know if I find anything.  If you wish to contribute a fix, please feel free to open a PR.  I should have some time for this next week.

Thanks

**Comment by luckylooke** [comment] 2017-02-02 19:31
I am sorry but I was using ol3gm just for presentation as one of possible solutions and we have choose another variant, so I am not going to fix it, I was willing to report it and I will test the fix afterwards but that is all time I can invest into this issue, thanks for understanding.

**Comment by adube** [comment] 2017-02-02 19:57
No problem.

**Comment by adube** [comment] 2017-02-22 16:22
Just for the record: I tested on our Mac OSX 10.10.5, on Chrome 56 and Safari 8.0.8: I could not see this issue, which is unfortunate.  I would have liked to see the issue in action to be able to work on this, but I will not be able to.

**Comment by luckylooke** [comment] 2017-02-22 18:19
I was just tested it again, and issue is still present. :/

**Comment by adube** [comment] 2017-02-22 18:48
Yeah... I really don't know what to do here...  I'll try asking a relative to test it on his Mac laptop.

I may also completely have to rethink how the zooming management is made with OL >= 3.20.1, but I currently lack the time to check on spare time.  Anyway, I'll let you know if I find something else regarding this.

**Comment by dmorissette** [comment] 2017-02-22 23:32
FYI, just tested on OSX 10.12.3 with Safari 10.0.3, Chrome Version 56.0.2924.87 (64-bit) and Firefox 51.0.1 (64-bit) and the Concept example works fine in all three.

Oh wait ... 

I just tested zooming with two-finger scroll on the touch pad and can reproduce the bug this way. So it's related to a difference between zooming with mouse wheel and zooming with touch pad.

**Comment by luckylooke** [comment] 2017-02-23 06:11
@dmorissette you are right, attached mouse scroll is working, and scrolling with two fingers on touch pad doesnt, thats very interesting. I am sorry I didnt realize that it can make difference.

**Comment by adube** [comment] 2017-02-23 13:13
Very interesting, indeed.  Thank you @dmorissette.

**Comment by jkossis** [comment] 2017-02-28 15:49
Any idea how to fix this?

**Comment by adube** [comment] 2017-02-28 16:01
I haven't looked at this yet, nor plan to work on this issue soon.  I also don't know how to fix this yet, but I'm keeping this in mind...  I'll post a comment if I begin working on this.

Reminder: just like with any open source project, the development of this library is driven by the funding we can get through customer projects, so if there are some limitations that are important to you and your organization, we'd be happy to provide you a quote for a support package or for working on those specific limitations, and of course you are also welcome to work on them yourself and contribute the fix.

Note that contributions have to meet some minimum quality requirements in order to be included in the official package, but that's the same as with any mature open source project.

**Comment by tsi** [comment] 2017-03-06 11:44
I experience this issue on osx after updating from:
```
    "ol3-google-maps": "0.11.1",
    "openlayers": "3.18.1",
```
to:
```
    "ol3-google-maps": "0.13.1",
    "openlayers": "3.20.1",
```

**Comment by tsi** [comment] 2017-03-06 13:18
```
    "ol3-google-maps": "0.12.3",
    "openlayers": "3.19.1",
```
still works well in my testing

**Comment by adube** [comment] 2017-03-06 13:23
#153 gives a good explanation.  At first, this is why I had close this issue as a duplicate because it seemed to be the same, but not quite exactly.  When a fix will be provided, it should fix both.

**Comment by boomdrak** [comment] 2017-06-14 07:49
Has anyone worked out a solution for this issue?
We are experiencing the same situation.

Zoom with pinch/touch phones/touch pad, that falls outside an integer zoom level returns a grey map.
When using a mouse-wheel with clicks or just + or - in map, zoom works just fine.

**Comment by adube** [comment] 2017-06-14 12:03
Would you please try this for me: define your own `ol.interaction.MouseWheelZoom` with `constrainResolution: true` set?

See: https://openlayers.org/en/latest/examples/mousewheel-zoom.html

This could fix the issue.

**Comment by JamiesWhiteShirt** [comment] 2017-06-15 09:05
It turns out @boomdrak's issue (our issue) was caused by something else cancelling animations. The animation cancelling nullifies the effect of `constrainResolution` on `PinchZoom`/`MouseWheelZoom`. This left the resolution in an invalid state, causing the map to go grey.

If you are experiencing issues with the constraint not working, make sure you're not accidentally cancelling animations.

**Comment by bampakoa** [comment] 2017-10-16 11:10
You could set `constrainResolution: true` in the map interactions so that the zoom level is always round up to the closest integer level. In my case, I set `constrainResolution` in the default interactions, since I use Google Maps only with OpenLayers.

```
 map = new ol.Map({
    interactions: ol.interaction.defaults({ constrainResolution: true }),
    view: new ol.View({
      center: [0, 0],
      zoom: 2
    })
  });

```

**Comment by ademus** [comment] 2017-10-25 17:57
Same pb for me on Firefox and the `constrainResolution: true` solution doesn't work. 
It seems that ol3gm.js simply doesn't  reacts at trackpad events. 
Strange because ol3.js does.

`ol.interaction.PinchZoom` in ol3gm-debug.js doesn't fire at all when I use the trackpad.

**Comment by adube** [comment] 2017-10-25 18:46
OLGM currently uses OpenLayers v4.1.1.  Maybe it would help to upgrade OpenLayers within OLGM.

If anyone is willing to work on this, I would be happy to review.

**Comment by bampakoa** [comment] 2017-10-25 19:52
@ademus Can you try with [this](http://plnkr.co/edit/o72v1ns3sxPWFfjwOeC4?p=preview) plnk?

**Comment by ademus** [comment] 2017-10-25 21:06
@bampakoa : it seeems to work !!!!
I lost `ol.animation.pan`, but it doesn't matter so much as long as everything else works fine.
I 'll check more tomorrow and I'll tell you if any others issues.

bampakoa : could u let me know a little more on this ol3gm.js version ?

thx u very much mate. :)

**Comment by bampakoa** [comment] 2017-10-26 08:35
@ademus I am glad it helped! The version of ol3gm is the same that is used in [ol3-google-maps examples](http://mapgears.github.io/ol3-google-maps/examples/).

**Comment by ademus** [comment] 2017-10-26 08:51
@bampakoa : LOL !!
I thought I used it too.  :/
Well thank you again for your help.

**Comment by bampakoa** [comment] 2017-10-26 08:56
@ademus I think is the same as [this](https://www.npmjs.com/package/ol3-google-maps) one from npm. This is what I use in my project after all.

**Comment by ademus** [comment] 2017-10-26 09:28
@bampakoa :
npm and mapgears.github.io should be the same. 
I don't remember where I picked up my ol3gm.js version but it was different.
Thx again for ur attention 🥇

**Comment by adube** [comment] 2017-10-26 12:14
>npm and mapgears.github.io should be the same.

Clarification: the versions of OLGM on npm and mapgears.github.io are always at the latest official version.

**Comment by adube** [comment] 2024-02-26 14:19
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352

**Closed as not planned by adube** 2024-02-26 14:19 UTC
