### ISSUE TITLE
Z-Index and order problems of rendering in layer collection

### ISSUE THREAD

**Issue by tds4u** [mapgears/ol3-google-maps#35] opened 2016-01-04 19:30 UTC
Hello,

please look at https://www.dreiharden.net/proxy/maps/dreiharden/

Change base map at top right to "Luftbild" and you'll see that the vector layer for POIs is now under all other layers. Clicking back to normal base map "Karte" all things are fine.

index 5, name markerpois, z-index 1000
index 4, name map4, z-index 10
index 3, name map3, z-index 10
index 2, name map2, z-index 10
index 1, name map1, z-index 10
index 0, name google, z-index 0

So, POIs are on top of z-index and last in rendering chain of OL3. But for google satellite it's under other WMS layers.

Please help fixing that. Thanks in advance.

**Comment by adube** [comment] 2016-01-05 12:59
This is due to the fact that WMS layers are not yet supported by OLGM.  Would you be willing to work on this feature ?

I would also be willing to work on this on behalf of Mapgears Inc. with proper funding.  If that interests you, please contact us at info@mapgears.com and we could evaluate the efforts required.

**Comment by fipp** [comment] 2016-01-27 10:16
I'm struggeling with a problem similar to this.

Take a look at this jsfiddle, where everything works as it should: https://jsfiddle.net/penn/mLrwbtj9/
What happens is that all the coordinates inside the `coordinates` gets painted as green circles (ol.style.Circle) immediately, then another layer with red circles are painted on top, with a 100ms circle delay of every red circle painted.

Now, if I swap the circle with an icon (`ol.style.Icon`), some of the icons gets painted, some do not, as illustrated in this other jsfiddle: https://jsfiddle.net/penn/mLrwbtj9/
The only thing that is changes is that I use `Icon` instead of `Circle`.

I'm not using a WMS layer here, I'm using a `ol.layer.Vector` in both cases. But the problem seems similar. Is this the same, or another issue really? Thanks for the advice!

**Comment by adube** [comment] 2016-02-24 13:33
I'm marking as duplicate of #51, as that other ticket will be the one detailing a solution for this.

I'm closing this one.

**Closed as completed by adube** 2016-02-24 13:33 UTC
Labels: duplicate
