### ISSUE TITLE
ol3-layerswitcher compability

### ISSUE THREAD

**Issue by fipp** [mapgears/ol3-google-maps#37] opened 2016-01-18 14:38 UTC
Hi! Has anyone here used `ol3-layerswitcher` together with `ol3-google-maps`? For some reason the google layer doesn't show correctly in my layer switcher:

<img width="323" alt="screen shot 2016-01-18 at 15 37 02" src="https://cloud.githubusercontent.com/assets/1716906/12393973/579ebce0-bdf9-11e5-9f1a-e79c3c63c43b.png">

Relevant pieces of code:

```
    var map = new ol.Map({
      target: 'map',
    });

    var googleLayer = new olgm.layer.Google({
      title: 'Kart (Google)',
      type: 'base',
    })
    map.addLayer(googleLayer);

    var shadedBing = new ol.layer.Tile({
      title: 'Kart (Bing)',
      type: 'base',
      source: new ol.source.BingMaps({
        key: bingKey,
        imagerySet: 'Road'
      })
    });
    map.addLayer(shadedBing);

    ...

    map.setView(new ol.View({
        projection: 'EPSG:900913',
        center: ol.proj.transform(
          settings.coords,
          'EPSG:4326',
          'EPSG:900913'
        ),
        zoom: 14
    }));

    var layerSwitcher = new ol.control.LayerSwitcher({});
    map.addControl(layerSwitcher);

    var olGM = new olgm.OLGoogleMaps({map: map});
    olGM.activate();

```

Any thoughts?

**Comment by adube** [comment] 2016-01-18 20:08
I'm pretty sure it should work properly.  Would you be willing in sharing a small example showing this on jsfiddle ? I could be able to debug from there and understand what's going on.

Thanks.

**Comment by fipp** [comment] 2016-01-19 08:13
Hi adube and thank you for answering swiftly! Here's a jsfiddle: https://jsfiddle.net/penn/swn6q0vs/5/

I referenced ol3-google-maps v0.3-12-gca50c71 from https://dev5.mapgears.com/ol3-google-maps/dist/ol3gm.js since I'm not able to build it (https://github.com/mapgears/ol3-google-maps/issues/33).

Cheers

**Comment by adube** [comment] 2016-01-19 13:47
Okay, I know what's wrong.  It's indeed a OLGM issue.  The `olgm.layer.Google` extends from `ol.layer.Group`.  In `ol.control.LayerSwitcher.prototype.renderLayer_`, it checks `if (lyr.getLayers)`, which returns `true` in the case of a Google layer since it extends from a Group layer.

I would make sense to make it inherit from `ol.layer.Base` instead.  If you're willing to work on a PR, it would be nice, but I know that in your case it would be hard since you're still not able to run the build (#33).

**Comment by fipp** [comment] 2016-01-19 14:58
My knowledge in OpenLayers is still not mature, but I would be willing to submit a PR for this yes, as soon as I can get building to work. I have been tasked with implementing Google Maps as an additional base layer in the OpenLayers application for a client, and I would rather not deliver a solution containing local hacks that has to be taken into consideration when upgrading in the future. 

Cheers, and thanks for your help so far!

**Comment by adube** [comment] 2016-01-19 15:30
I understand.  Let us know how your progress goes.

**Comment by adube** [comment] 2016-02-05 14:13
@fipp with #43 now fixed, you can carry on with providing a patch, if you're willing to.  Please, let us know.

**Comment by adube** [comment] 2016-02-24 13:30
@fipp Are you still facing this issue ?  If so, would you like to work on a PR ?

**Comment by pcahard** [comment] 2016-09-13 16:06
hello adube, when you create olgm.layer.Google, add the "combine" parameter, this works for me.

`
var googleLayer = new olgm.layer.Google({
      title: 'Kart (Google)',
      type: 'base',
      combine: true
    });
`

**Comment by adube** [comment] 2016-09-13 17:04
Thanks for sharing thiss, @pcahard.  I think it's safe to assume that this is no longuer an issue, so I'll close it for now.

**Comment by tomn98** [comment] 2016-09-14 01:12
@adube Has that issue you mentioned on Jan 19 about "olgm.layer.Google extends from ol.layer.Group" been resolved yet?  You said it was best to extend from ol.layer.Base instead.  I'm pretty sure that's why my code is not working since my two layers, one of which is an olgm.layer.Google, are inside an ol.layer.Group.  Below is the relevant snippet.  The _googleLayer_Road_ layer doesn't display, but the _arcGISTileLayer_ displays fine.

```
var arcGISTileLayer = new ol.layer.Tile({
  title: 'ArcGIS Tile',
  type: 'base',
  source: new ol.source.TileArcGISRest({
        url: url
  })
});

var googleLayer_Road = new olgm.layer.Google({
  title: 'Google (Road)',
  type: 'base',
  combine: true  
});

var map = new ol.Map({
  layers: [
       new ol.layer.Group({
           'title': 'Base maps',
           layers: [ arcGISTileLayer, 
                     googleLayer_Road
           ]
       })
  ],

  target: 'map',
  view: new ol.View({
    center: center2Transform,
    zoom: 6
  })
});
```

**Comment by adube** [comment] 2016-09-14 12:20
Oh, that's right.  I had forgotten about that.  Thanks for pointing this out.  I'll reopen this issue.

If you're willing to work on a PR, I'd be happy to review it.

**Comment by tomn98** [comment] 2016-09-14 23:12
I'm not familiar with the ol3-google-maps code, but I went ahead and took a quick look at the source to see how I might be able to change it to inherit from ol.layer.Base.  I discovered a few roadblocks right away: 
-  I'm not familiar with the Google Closure Library, so the syntax in the file googlelayer.js seems foreign to me.
- I might be wrong, but I have a feeling a change in inheritance like this will affect other areas of the code, which I don't have any expertise in.
- It'll take me a while to set up a development environment correctly. 

Anybody else willing to take on making this change?

**Comment by adube** [comment] 2016-09-15 13:22
I'd be interested, but my schedule is pretty much booked for a while.  You could fund this, if you're interested seeing this fixed as soon as possible.  If you do, send an email to info at mapgears dot com, refering this issue.

**Comment by geopamplona** [comment] 2017-03-07 09:40
I'm trying to do the same. Upload osm + google maps using ol3-layerswitcher. But it does not load correctly, ie all layers are displayed correctly but when I select osm, google layers are not loaded and returns the following error:

TypeError: this.cache_ [index] is undefined [Learn more] ol3gm-debug.js: 83477: 5
Olgm.herald.VectorFeature.prototype.unwatchFeature_ ol3gm-debug.js: 83477: 5
For-self self-hosted
Olgm.herald.VectorFeature.prototype.deactivate ol3gm-debug.js: 83393: 3
Olgm.herald.VectorSource.prototype.deactivateCacheItem_ ol3gm-debug.js: 83663: 3
For-self self-hosted
Olgm.herald.VectorSource.prototype.deactivate ol3gm-debug.js: 83651: 3
Olgm.herald.Layers.prototype.deactivateGoogleMaps_ ol3gm-debug.js: 91469: 3
Olgm.herald.Layers.prototype.toggleGoogleMaps_ ol3gm-debug.js: 91516: 5
Ol.events.bindListener_ / boundListener ol3gm-debug.js: 3431: 12
Ol.events.EventTarget.prototype.dispatchEvent ol3gm-debug.js: 3849: 11
Ol.Object.prototype.notify ol3gm-debug.js: 4262: 3
Ol.Object.prototype.set ol3gm-debug.js: 4282: 7
Ol.layer.Base.prototype.setVisible ol3gm-debug.js: 20531: 3
Ol.control.LayerSwitcher.prototype.setVisible _ / <ol3-layerswitcher.js: 158: 21
Ol.control.LayerSwitcher.forEachRecursive / <ol3-layerswitcher.js: 243: 13
For-self self-hosted
Ol.Collection.prototype.forEach ol3gm-debug.js: 12408: 3
Ol.control.LayerSwitcher.forEachRecursive ol3-layerswitcher.js: 242: 9
Ol.control.LayerSwitcher.prototype.setVisible_ ol3-layerswitcher.js: 156: 13
Ol.control.LayerSwitcher.prototype.renderLayer_ / input.onchange

I use stable libraries, i download it yesterday.
I load the layers this way in OL3:
         Layers: [
                base,
                New olgm.layer.Google ({
                    Title: 'NORMAL (Google)',
// visible: true,
                    Type: 'base',
                    Combine: true}),
                New olgm.layer.Google ({
                    MapTypeId: google.maps.MapTypeId.SATELLITE,
                    Title: 'SATELLITE (Google)', type: 'base', match: true
                }),
                New olgm.layer.Google ({
                    MapTypeId: google.maps.MapTypeId.TERRAIN,
                    Title: 'TERRAIN (Google)', type: 'base', combine: true
                })
            ],

        Var base = new ol.layer.Tile ({
            Title: 'OSM (OpenStreetMap)',
            Name: lang.getLayerNames.OpenStreetMap,
// baselayer: true,
// combine: true,
            Type: 'base',
            Source: new ol.source.OSM (),
        });

For now my solution is not to use the OSM layer, which is very bad, not being able to use both providers.

Thank you

Good job !

**Comment by geopamplona** [comment] 2017-03-07 10:22
Apparently I have found a solution to the problem by modifying line 83479
Modifying the function "olgm.herald.VectorFeature.prototype.unwatchFeature_"
In synthesis control the deletion of the cache
Change the line
     This.cache_ [index] .herald.deactivate ();
     // remove from cache
     This.cache_.splice (index, 1);

to

     If (this.cache_.length> 0)
     {
                 This.cache_ [index] .herald.deactivate ();
     // remove from cache
     This.cache_.splice (index, 1);
     }

I am not an expert in this code but for now this is valid for me

**Comment by adube** [comment] 2017-03-07 13:31
@geopamplona Would you please provide a PR for this?  Thank you.

**Comment by ciriux** [comment] 2017-03-29 02:10
Hi, is there a solution to this issue? Im experiencing the same problem.

**Comment by adube** [comment] 2017-03-29 12:07
Not for the moment, no.  A contribution would be welcome.

**Comment by mstenta** [comment] 2019-08-16 19:34
I just created a pull request which alters the GoogleLayer class to extend from `ol.layer.Layer` instead of `ol.layer.layerGroup`. It was pretty simple - aside from changing the class declaration, the only other thing I needed to do was set `this.type = LayerType.TILE` (following the pattern of `ol.layer.Tile`).

https://github.com/mapgears/ol3-google-maps/pull/259

This seems to work the same as it did before, although now you don't need to add `combine: true` to get it to work with LayerSwitcher.

However, it *still* does not fix the specific issue described in @tomn98's comment above: https://github.com/mapgears/ol3-google-maps/issues/37#issuecomment-246876398

If I put the Google layers in the root map layers collection, they work.  But if I put them inside a LayerGroup (eg: "Base layers"), they do not work.  You can toggle between them, so nothing in the code seems to break... you just see a white map screen when you toggle to a Google layer.

So the fact that GoogleLayer extended from LayerGroup may *not* have been the cause of that issue after all...

**Comment by adube** [comment] 2019-08-16 19:42
I took a quick look at the ol-layerswitcher code and it checks if the OL layer has the `getLayers` method to determine if it's a Group.  Without checking further, we can guess that it was a problem that OLGM's layer inherited from Group.

See: https://github.com/walkermatt/ol-layerswitcher/blob/master/src/ol-layerswitcher.js#L390

We now be facing an other issue.

**Comment by mstenta** [comment] 2019-08-16 19:46
Yes that's correct - and that's why it was necessary to set `combine: true` for a GoogleLayer to work in layerswitcher. With #259, that is no longer necessary...

But it still doesn't work inside a sub-group... So I agree - it might be another issue.  :-/

But, #259 is still a good first step... as soon as I can figure out why Travis test failed. :-)

**Comment by mstenta** [comment] 2019-08-20 21:04
> But it still doesn't work inside a sub-group... So I agree - it might be another issue. :-/

I just tested this with a bare minimum setup: one Google layer inside one LayerGroup (no other layers involved). I just see a white screen on the map. Controls and everything else seem to work though.

Notably, looking at the Network tab in Firefox, there are no requests being made to load Google tiles.

Just the loading of `https://maps.googleapis.com/maps/api/js?v=3&key=[key]` and a call to `https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?...`.

**Comment by mstenta** [comment] 2019-08-20 21:14
Another (possibly unrelated) issue I'm seeing: if I have a vector feature layer rendered over a Google layer, and I uncheck the vector layer in the layer switcher, it does not disappear from the map. However, if I switch from a Google layer to the OpenStreetMap layer, it disappears. And then if I switch back to the Google layer it is also gone there.

If I then re-enable it by clicking the checkbox again, it does not show up on the Google layer, but does when I switch to OSM.

So it seems that the checkboxes for toggling layer visibility are not relaying updates to the Google layers.

**Comment by mstenta** [comment] 2019-08-20 21:19
So just a quick summary for anyone reading up to this point, it seems that there are (currently) 3 issues with `ol3-google-maps` + `ol-layerswitcher` compatability:

1. Because `GoogleLayer` inherits from `LayerGroup`, you must add `combine: true` to your Google map layer definition for it to work with layer switcher. This is fixed by https://github.com/mapgears/ol3-google-maps/pull/259
2. If you try to put a `GoogleLayer` inside a `LayerGroup` (layer switcher supports nested layer groups, eg: https://raw.githack.com/walkermatt/ol-layerswitcher/master/examples/select-groups.html) then you see a white screen instead of Google tiles (see comment above: https://github.com/mapgears/ol3-google-maps/issues/37#issuecomment-523194185).
3. Checking/unchecking layer switcher checkboxes does not update overlays on the Google layer (see comment above: https://github.com/mapgears/ol3-google-maps/issues/37#issuecomment-523197462)

So https://github.com/mapgears/ol3-google-maps/pull/259 is a first step, but there are two other issues to debug here...

**Comment by adube** [comment] 2019-08-21 14:31
@mstenta Thank you very much for these details.

**Comment by mstenta** [comment] 2019-08-22 14:32
I think issues 2 and 3 described above are related. And I'm also noticing that sometimes I get a white screen when I toggle back and forth between Google layers and another layer (like OSM or MapBox). And that happens even when they are all on the root layer level (not in a sub-group).

I don't know enough about how the "herald" code works to relay actions back and forth to the Google layers - but it seems to be related to that perhaps. Maybe some actions from the layer switcher (like toggling layer checkboxes/radios on/off) are not being picked up. That gives me hope that it's not going to be a very difficult thing to fix.

Is there any documentation to help me get up to speed on how the herald code works?

**Comment by mstenta** [comment] 2019-12-18 20:51
Issue 1 described above was fixed with https://github.com/mapgears/ol3-google-maps/pull/259

So it's just issues 2 (google layers in a layer group) and 3 (feature visibility sync) that remain on this (unless others are discovered).

**Comment by mstenta** [comment] 2019-12-19 19:04
Huh. Interesting... I'm working on adding support for OL6+ (#282 ), and in my testing it appears that issue number 3 described above (feature visibility sync) is no longer an issue! I'm not able to replicate it any more.

**Comment by mstenta** [comment] 2019-12-20 20:06
I split the "issue 2" described above out to #285 - it is not specifically related to ol3-layerswitcher compatibility, so it doesn't need to be solved in this issue.

Think that means we can close this issue!

**Comment by adube** [comment] 2019-12-23 13:34
Indeed we can.  Thank you for the details!

**Closed as completed by adube** 2019-12-23 13:34 UTC
Labels: bug
