### ISSUE TITLE
Problem with getStroke

### ISSUE THREAD

**Issue by marketingpmi** [mapgears/ol3-google-maps#70] opened 2016-05-16 09:12 UTC
Hello,
when i load for the first time my olgm map, appear in console these errors
"ol3gm.js:400 Uncaught TypeError: Cannot read property 'r' of undefined"
and
"ol3gm.js:244 Uncaught TypeError: d.getStroke is not a function"
and the dots of polygon on layer are very bigger than normal.

I think probably it's link on a centroid problem on ol.js (row 10811):
    l.Nc = function(b) {
        vp(this, b);
        this.k()
    };

What is the problem?
How can i fix it?

thank you
![screenshot-localhost 2016-05-16 11-10-42](https://cloud.githubusercontent.com/assets/7781896/15285352/e23af732-1b56-11e6-826c-fbd10e10f274.png)

**Comment by IsmayilAqazade** [comment] 2016-05-16 11:35
the same problem 
ol3gm.js:27 Uncaught TypeError: d.getStroke is not a function

**Comment by adube** [comment] 2016-05-16 12:00
Would you please provide a small demo featuring the issue, maybe with JSFiddle ?

**Comment by IsmayilAqazade** [comment] 2016-05-16 12:18
the problem is in style function.When i use style object problem solved .Why don't i use style function?

**Comment by adube** [comment] 2016-05-16 12:39
Style functions are not supported, as documented in the limitations: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#style-functions

There's currently no plan to support them either.

**Comment by marketingpmi** [comment] 2016-05-16 13:10
Sorry but i don't use a style object neither manipulate style.
The problem is present in this function but i don't understand why (ol3gm.js - row 239).

```
function fa(a, b) {
        var c = null,
            d = C(a);
        if (d) {
            var c = {},             
                e = d.getStroke();

            if (e) {
                var f = e.getColor();
                f && (c.strokeColor = x(f), f = B(f), null !== f && (c.strokeOpacity = f));
                (e = e.getWidth()) && (c.strokeWeight = e)
            }
            if (e = d.getFill())
                if (e = e.getColor()) c.fillColor = x(e), e = B(e), null !== e && (c.fillOpacity = e);
            if (f = d.getImage()) {
                d = {};
                e = {};
                if (f instanceof ol.style.Circle) {
                    e.path = google.maps.SymbolPath.CIRCLE;
                    var h = f.getStroke();
                    if (h) {
                        var k = h.getColor();
                        k && (e.strokeColor = x(k));
                        e.strokeWeight = h.getWidth()
                    }
                    if (h = f.getFill())
                        if (h = h.getColor()) e.fillColor =
                            x(h), h = B(h), e.fillOpacity = null !== h ? h : 1;
                        (f = f.getRadius()) && (e.scale = f)
                } else f instanceof ol.style.Icon && ((h = f.getSrc()) && (e.url = h), h = f.getScale(), (k = f.getAnchor()) && (e.anchor = void 0 !== h ? new google.maps.Point(k[0] * h, k[1] * h) : new google.maps.Point(k[0], k[1])), (k = f.getOrigin()) && (e.origin = new google.maps.Point(k[0], k[1])), f = f.getSize()) && (e.size = new google.maps.Size(f[0], f[1]), void 0 !== h && (e.scaledSize = new google.maps.Size(f[0] * h, f[1] * h)));
                Object.keys(d).length ? c.icon = d : Object.keys(e).length && (c.icon =
                    e)
            }
            0 === Object.keys(c).length ? c.visible = !1 : void 0 !== b && (c.zIndex = 2 * b)
        }
        return c
    };
```

**Comment by adube** [comment] 2016-05-16 13:24
As I said, you can't use style functions with OLGM.  It's not currently suported to do so.  See the limitations.

**Comment by marketingpmi** [comment] 2016-05-16 13:27
Ok, thank you for your answer but problem is inside the code of ol3gm.
Can you suggest me a workaround, please?
thank you

**Comment by adube** [comment] 2016-05-16 14:55
This is not a bug.  You must not use StyleFunctions with OLGM as it is stated in the limitations.  There is no other workaround than "don't use StyleFunctions" with OLGM.  I'm sorry that I can't be of more help regarding this for now.

If you absolutely need this, then you're welcome to create a Pull Request adding this support or you can contact info at mapgears dot com if you wish to fund the development of this.

To my knowledge, I think it's impossible to support style functions with OLGM.

**Comment by adube** [comment] 2016-07-22 19:42
I'm closing this.  See the limitations: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#style-functions

**Closed as completed by adube** 2016-07-22 19:42 UTC
Labels: wontfix
